[package]
name = "patcher"
version = "1.0.0"
authors = ["Daniel Santana <danielgsantana@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.1"
clap = "2.33"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
serde_json = "1.0"
structopt = "0.2"

[profile.release]
lto = true